using UnityEngine;
using System.Collections;

public class LevelPicker : MonoBehaviour {

	private GameManager GM;
    new LevelBuilder level_builder_script;
	
	void Awake() 
	{
		GM = GameManager.instance;
        level_builder_script = GameObject.FindGameObjectWithTag(Tags.game_manager).GetComponent<LevelBuilder>();
		DontDestroyOnLoad(this); // to allow the scene to change
	}
	
	void Update()
    {
	}

	IEnumerator LoadAndBuildLevelRoutine(int level)
	{
		Application.LoadLevel(3);
		yield return null;
        level_builder_script.BuildLevel(level); // Level parameter will be pulled from button number
		GM.SetToPreGame();
		Destroy(transform.gameObject);
	}
	
	// Can be auto generated by building buttons from a list/dict
	public void Level1Button() 
	{
		StartCoroutine(LoadAndBuildLevelRoutine(1));
	}
}
